### PR TITLE
nodeHttp: explicitly set Content-Length

### PR DESCRIPTION
**Pull request by ishitatsuyuki**
This is to avoid unnecessarily making the requests chunked, which are not needed as we don't support client-side streaming yet.

Ref: GAE's frontend is too retarded to handle chunked encoding. https://issuetracker.google.com/issues/71003088

### CODE REVIEW

**Comment by ishitatsuyuki** [comment]
ArrayBufferView doesn't make sense and I'll be changing the typing to UInt8Array tomorrow to resolve compile issues.

**Comment by ishitatsuyuki** [comment]
CI green. Please review.

**Comment by easyCZ** [comment]
@ishitatsuyuki Thanks for your PR! Would it be possible to add unit tests to ensure we don't break functionality going forward?

**Comment by ishitatsuyuki** [comment]
Hmm, I'm not sure if unit tests are deemed necessary. If absolutely needed, it would be an assertion on `Content-Length` in Go handler.

**Comment by easyCZ** [comment]
@ishitatsuyuki Could you please rebase the PR?

**Comment by ishitatsuyuki** [comment]
This can be no longer done reasonably due to the interface change; closing.

**Comment by public** [comment]
This makes using the Node transport quite tricky from Python as most WSGI servers have pretty poor chunked encoding support. Would you be interested in a new PR that achieves the same effect as here?

**Comment by jonnyreeves** [comment]
Yes please, although perhaps it could be made configurable when the
transport instance is created?

**Pull request closed without merging**
