### PR TITLE
Minor fixes

### PR DESCRIPTION
**Pull request by johanbrandhorst**
1. Install stable version of `dep` in CI.
1. Regenerate Gopkg.lock with new `dep`.
1. Add `protoc-gen-go` as explicit dependency.
1. Install dep locked version of `protoc-gen-go` in CI.

### CODE REVIEW

**Comment by johanbrandhorst** [comment]
On second thought, it seems like this will run about 30 tests for all 4 support architectures. Do we want to support a single architecture in CI instead? I'm hesitant to leave it at 1.8.

**Comment by easyCZ** [comment]
Good spot. We could bump it to 1.10. Running on multiple go versions will result in even more flakes. I'd be inclined to run just on one and perhaps attempt to find a path forward to improve reliability of the tests

**Comment by johanbrandhorst** [comment]
Any reason not to change it to 1.11? Is Improbable still running 1.10 internally ;)? I agree we should run just 1 version but I'd be inclined to run latest if possible.

**Comment by easyCZ** [comment]
We are indeed on 1.10 still but it should not matter for us internally as we can upgrade when needed.

Yeah let's go with 1.11 then.

**Pull request merged**
