### PR TITLE
Add Release Script

### LINKED ISSUE #43: Add scripts for creating releases and tagging them in Github
https://help.github.com/articles/creating-releases/

We should have a branch for a release + a set of release notes in the Releases page:

https://github.com/c4milo/github-release
https://github.com/aktau/github-release/releases

may be helpful.

We should definitely package the build of grpc-proxy for linux like that.

### PR DESCRIPTION
**Pull request by jonnyreeves**
Build and publish to Github and NPM; includes binaries for the grpcweb-proxy for linux and macOS.

Example run below, note that it fails on the last step (npm publish) as I don't have rights to publish artifacts to npm.

```
Jonnys-Air:grpc-web jonny$ ./release.sh 
Reading version from /Users/jonny/Projects/gocode/src/github.com/improbable-eng/grpc-web/ts/package.json.
Build v0.3.0? y
Building grpcweb-proxy
Building grpcweb-client
Github Release Notes (terminate with ctrl-d):
Testing release script
Release v0.3.0? y
Creating Github Release
Uploading grpcweb-client_0.3.0.zip...
Uploading grpcweb-proxy_0.3.0_darwin_amd64...
Uploading grpcweb-proxy_0.3.0_linux_amd64...
Done
Publishing to npm
npm ERR! publish Failed PUT 403
```

Instead of creating a release branch; this script creates a tag and uploads artefacts to github where they can be downloaded from the releases page.

Note that whilst this script will 'tag' a release on NPM as a beta based on the value found in the `ts/package.json`, the github release will be not be marked as a pre-release until https://github.com/c4milo/github-release/pull/8 lands.

Fixes #43.

### CODE REVIEW

**Comment by jonnyreeves** [comment]
@mwitkow could you ptal?

**Comment by mwitkow** [comment]
Can you make sure the branching strategy also works for Golang
https://dave.cheney.net/2016/06/24/gophers-please-tag-your-releases

Preferably using
http://labix.org/gopkg.in ?

**Comment by mwitkow** [comment]
Basically so we can make it play nice with https://github.com/golang/dep

**Comment by easyCZ** [comment]
I believe this is no longer required as the project already uses `dep`, no?

**Comment by johanbrandhorst** [comment]
Is this still relevant?

**Comment by easyCZ** [comment]
Closing this. If it is still relevant then please comment and we can re-open.

**Pull request closed without merging**
