### PR TITLE
Update grpc-go, golang/protobuf dependencies

### LINKED ISSUE #236: Update Go dependencies
Our gRPC dependency is 1.8 which is almost a year old, and chiefly to work around issues like #216. We should make an effort to update the Go dependencies to get security fixes and new features.

### LINKED ISSUE #393: Crash in vendored gRPC-Go version
**Versions of relevant software used**
/grpcwebproxy-v0.9.1-linux-x86_64

**What happened**
Not able to bridge grpc server with web client, 
after the first call the first part of the log is output, the second call leads to a crash
./grpcwebproxy-v0.9.1-linux-x86_64 --backend_addr=10.251.177.181:50051 --run_tls_server=false --allow_all_origins

**What you expected to happen**
Sweet working grpc-web proxy.

**How to reproduce it (as minimally and precisely as possible)**:
The intention is to replace envoy for some setups in the for the following product. 
Server: https://github.com/volvo-cars/signalbroker-server
Client: https://github.com/volvo-cars/signalbroker-web-client

**Full logs to relevant components**

<details>Logs
<p>

```
./grpcwebproxy-v0.9.1-linux-x86_64 --backend_addr=10.251.177.181:50051 --run_tls_server=false --allow_all_origins --backend_max_call_recv_msg_size=5242880 --use_websockets
INFO[0000] dialing to target with scheme: ""             system=system
INFO[0000] using websockets                             
INFO[0000] ccResolverWrapper: sending new addresses to cc: [{10.251.177.181:50051 0  <nil>}]  system=system
INFO[0000] listening for http on: [::]:8080             
INFO[0000] pickfirstBalancer: HandleSubConnStateChange: 0xc420099680, CONNECTING  system=system
INFO[0000] pickfirstBalancer: HandleSubConnStateChange: 0xc420099680, READY  system=system
INFO[0002] pickfirstBalancer: HandleSubConnStateChange: 0xc420099680, TRANSIENT_FAILURE  system=system
INFO[0002] pickfirstBalancer: HandleSubConnStateChange: 0xc420099680, CONNECTING  system=system
ERRO[0002] finished streaming call                       error="rpc error: code = Internal desc = stream terminated by RST_STREAM with error code: PROTOCOL_ERROR" grpc.code=Internal grpc.method=GetConfiguration grpc.service=base.SystemService grpc.start_time="2019-04-17T15:49:47+02:00" grpc.time_ms=3 span.kind=server system=grpc
INFO[0002] pickfirstBalancer: HandleSubConnStateChange: 0xc420099680, READY  system=system


panic: close of closed channel

goroutine 30 [running]:
github.com/improbable-eng/grpc-web/vendor/google.golang.org/grpc/transport.(*Stream).finish(...)
        /Users/jonny/Projects/grpc-web/src/github.com/improbable-eng/grpc-web/vendor/google.golang.org/grpc/transport/transport.go:400
github.com/improbable-eng/grpc-web/vendor/google.golang.org/grpc/transport.(*http2Client).handleGoAway(0xc420085680, 0xc4201b6f60)
        /Users/jonny/Projects/grpc-web/src/github.com/improbable-eng/grpc-web/vendor/google.golang.org/grpc/transport/http2_client.go:1024 +0x1c6
github.com/improbable-eng/grpc-web/vendor/google.golang.org/grpc/transport.(*http2Client).reader(0xc420085680)
        /Users/jonny/Projects/grpc-web/src/github.com/improbable-eng/grpc-web/vendor/google.golang.org/grpc/transport/http2_client.go:1203 +0x4f1
created by github.com/improbable-eng/grpc-web/vendor/google.golang.org/grpc/transport.newHTTP2Client
        /Users/jonny/Projects/grpc-web/src/github.com/improbable-eng/grpc-web/vendor/google.golang.org/grpc/transport/http2_client.go:272 +0xbf1
```

</p>
</details>

**Anything else we need to know**
Thanks a lot, hope this can be our natural envoy replacer for ARM enviroments.

Server is written in Elixir and uses: https://github.com/elixir-grpc/grpc
Bridging works well using envoy (which we would like to replace for ARM targets)

### PR DESCRIPTION
**Pull request by johanbrandhorst**
Update golang/protobuf to 1.3.0, update grpc-go to
1.20.1. The grpc-go upgrade requires removing the drop
tests as we no longer have access to the underlying transport.

Fixes #236. Hopefully fixes #393.

### CODE REVIEW

**Comment by johanbrandhorst** [comment]
I decided to follow this up with a `dep ensure -update` to pull in any new versions. Hopefully the tests will pass.

**Comment by johanbrandhorst** [comment]
I've fixed the tests, but could I please get another look at this? I know we're making a new release imminently, and I think we need to consider this for the next one. The gRPC version we're using is almost 1.5 years old, with many bug fixes and improvements having gone in since.

**Comment by jonny-improbable** [comment]
Waiting for tests to pass, but code-changes LGTM. cc @devnev, @easyCZ and @MarcusLongmuir.

**Comment by johanbrandhorst** [comment]
Not sure whats up with the tests :thinking:

**Comment by johanbrandhorst** [comment]
Gonna try to close-reopen this and see if the tests rerun

**Comment by johanbrandhorst** [comment]
@jonnyreeves looks like the tests passed on the rerun, could you approve this?

**Comment by jonny-improbable** [comment]
@MarcusLongmuir we discussed this a couple of days ago; you said you might know a way of keeping the drop tests despite the loss of the the `StreamFromContext` method - please can you share your thoughts otherwise we should merge this change as is for the benefit of the wider community.

**Comment by johanbrandhorst** [comment]
Bump, I'd be happier merging this and adding back the tests later than waiting much later with this. I can rebase and merge this if you're happy with it @jonny-improbable?

**Comment by johanbrandhorst** [comment]
Rebased

**Comment by johanbrandhorst** [comment]
:relieved:

**Pull request merged**
