### PR TITLE
check closed

### PR DESCRIPTION
**Pull request by mwei0210**
https://github.com/improbable-eng/ts-protoc-gen/issues/88

### CODE REVIEW

**Comment by bclermont** [comment]
this is very annoying to have the console filled with error, can this be merged?

**Comment by jonny-improbable** [comment]
LGTM, all failing tests appear to be unrelated to this change.

**Comment by bclermont** [comment]
Time to merge!

**Comment by jonny-improbable** [comment]
@mwei0210 please could you rebase your change against master? The flaking tests have been improved so you should get a pass now.

**Comment by mwei0210** [comment]
@jonny-improbable looked like it failed one of the test, enlighten me on whats wrong with the test see if i could come out with a fix?

**Comment by jonny-improbable** [comment]
I'm guessing that a flake as it only failed in specific version of firefox and passed in other versions of said browser. I've re-triggered the build, let's pray to the gods of Saucelabs 🙏

**Comment by mwei0210** [comment]
it failed again :(

**Comment by jonny-improbable** [comment]
Nope, [Build #737](https://travis-ci.org/improbable-eng/grpc-web/builds/424284530) passed; merging.

**Comment by jonny-improbable** [comment]
Thanks for persevering @mwei0210.

**Comment by mwei0210** [comment]
Thanks guys!

**Pull request merged**
